# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fbc9373c64a40b88fc9ea9dc74391e28"
name = "quizora-quiz-app\r"
application_url = "https://quizora-shopify-app-tv3l.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://quizora-shopify-app-tv3l.vercel.app/auth/callback",
  "https://quizora-shopify-app-tv3l.vercel.app/auth/shopify/callback",
  "https://quizora-shopify-app-tv3l.vercel.app/api/auth"
]
